### ISSUE TITLE
from [develop:frontend] ./node_modules/gatsby-plugin-postcss/node_modules/postcss-loader/dist/cjs.js): [develop:frontend] TypeError: Cannot read property '700' of undefined

### ISSUE THREAD

**Issue by chakerben** [strapi/strapi-starter-gatsby-corporate#27]
i worked and developped in this template, after trying my project on other server , 
i got this error : 
<img width="1328" alt="Capture d’écran 2021-11-10 à 00 07 16" src="https://user-images.githubusercontent.com/8640975/141020050-dc8b6884-aea1-4294-a545-adfde3858695.png">
<img width="1328" alt="Capture d’écran 2021-11-10 à 00 07 36" src="https://user-images.githubusercontent.com/8640975/141020056-5b30346b-369e-4931-9d31-d93242668a3a.png">
<img width="1328" alt="Capture d’écran 2021-11-10 à 00 07 52" src="https://user-images.githubusercontent.com/8640975/141020059-8b82f29c-b3be-4e63-b356-b0079783ef46.png">
<img width="1328" alt="Capture d’écran 2021-11-10 à 00 08 17" src="https://user-images.githubusercontent.com/8640975/141020062-bc2a885e-ff6e-42f0-8da7-5d55a0368dbd.png">

**Comment by cedricdiop** [comment]
What was the soluton?
