### ISSUE TITLE
Schema not updating?

### ISSUE THREAD

**Issue by yakou32** [strapi/strapi-starter-gatsby-corporate#6]
Not so sure where to ask this so I hope this is the right spot...
Also, I guess that this might be a relevant question for beginners that are interested by a strapi-starter-gatsby-*

Interpreting the readme which presents how to update a section, I guess that updating a component should be performed this way:

1. Create a new component in Strapi
2. Use this component in a page, adding data
(at this stage, the GraphQL schema is updated on Strapi's side)
3. Update the query(ies) in Gatsby accordingly
4. Create a React component that takes a data prop in the frontend, add this component
5. Link this React component

My main issue is that build fails at step 3: the query fails as a the new entries are not accessible from Gatsby.

Indeed, comparing the schemas from Strapi (http://localhost:1337/graphql) and Gatsby (http://localhost:8000/__graphql), I can see that the schemas differ (and btw, there is no permission issue).

I restarted the server and, although success messages do appear, the schema is not updated.
```
success createSchemaCustomization - 0.003s
success Checking for changed pages - 0.001s
success source and transform nodes - 0.462s
success building schema - 0.263s
```

The old schema is still fully available in Gatsby's GraphiQL
The compilation must be achieved to access this GraphiQL UI, so I had to remove any new schema entry, and I also removed some part of the original query (e.g. logo from navbar in `layout.js`) to simulate a difference. This way, I can access the GraphiQL UI, and I can see that there is still a navbar>logo in the schema...

In this exemple, the GraphiQL documentation shows this:
> Strapi_ComponentLayoutNavbar
> - id: ID!
> - logo: Strapi_UploadFile
> - links: [Strapi_ComponentLinksLink]
> - button: Strapi_ComponentLinksButtonLink

So, how to update this component?

I also tried to [force refresh Gatsby's content](https://www.gatsbyjs.com/docs/refreshing-content/)  but I'm not sure where to put the `.env.development` file in the monorepo. It seems not to work, wether at the root, or in the  `frontend` folder.
```
ENABLE_GATSBY_REFRESH_ENDPOINT=true
```

Well, I'm a newbie with both Gatsby and Strapi, and I'm facing these difficulties to make them work together since my very first attempts. I was really hoping from the strapi-starter-gatsby-* projects for my use case.

Is there anything I miss?

**Comment by markkaylor** [comment]
Hi @yakou32,  I was able to reproduce the issue.  Could you try running the `clean` script inside the frontend directory to remove the cache. 
 
``
yarn clean or npm run clean
``

**Comment by markkaylor** [comment]
> I also tried to force refresh Gatsby's content but I'm not sure where to put the .env.development file in the monorepo. It seems not to work, wether at the root, or in the frontend folder.
> 
> ENABLE_GATSBY_REFRESH_ENDPOINT=true

The `.env.development` should be in the frontend directory.  This is missing in the gatsby config:

```
require("dotenv").config({
  path: `.env.${process.env.NODE_ENV}`,
})
```
After adding it and testing with: `curl -X POST http://localhost:8000/__refresh` it appears to be working.

I will open a PR for the env config

**Comment by yakou32** [comment]
Hi @markkaylor 
Thanks for your help!

I did `yarn cache clean`, and was able to set the environment variable.

At this point, GraphiQL shows a schema that matches Strapi's. So that's quite encouraging :)

**Comment by dustinlacewell** [comment]
I just ran into this issue late at night and spent hours flailing around until I found this closed issue.

**Comment by karlopenguini** [comment]
Hello, has there been any updates as to why this problem is still persistent in gatsby v 4.5.2 and strapi v 4.0.5 ?
